# Generated by Django 2.2.7 on 2020-01-09 15:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200109_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
